<?php $presets["skin5"] = array (
  'preset' => 'skin5',
  'header-logo_regular' => 
  array (
    0 => '/inc/presets/images/full/skin5.header-logo-regular.png?w=49&h=78',
    1 => 0,
  ),
  'header-logo_hd' => 
  array (
    0 => '/inc/presets/images/full/skin5.header-logo-hd.png?w=98&h=156',
    1 => 0,
  ),
  'bottom_bar-logo_regular' => 
  array (
    0 => '/inc/presets/images/full/skin1.bottom-bar-logo-regular.png?w=27&h=53',
    1 => 0,
  ),
  'bottom_bar-logo_hd' => 
  array (
    0 => '/inc/presets/images/full/skin1.bottom-bar-logo-hd.png?w=54&h=106',
    1 => 0,
  ),
  'general-bg_color' => '#ffffff',
  'general-bg_opacity' => 100,
  'general-bg_ie_color' => '#252525',
  'general-bg_image' => 
  array (
    'image' => '',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'top',
  ),
  'general-bg_fullscreen' => false,
  'general-layout' => 'boxed',
  'general-boxed_bg_color' => '#d2d3d7',
  'general-boxed_bg_image' => 
  array (
    'image' => '/inc/presets/images/full/skin5.general-boxed-bg-image.jpg',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'top',
  ),
  'general-boxed_bg_fullscreen' => '1',
  'general-responsive' => '1',
  'general-hd_images' => '1',
  'general-accent_bg_color' => '#2a83ed',
  'general-thick_divider_style' => 'style-5',
  'general-thin_divider_style' => 'style-1',
  'general-next_prev_in_blog' => '1',
  'general-next_prev_in_portfolio' => '1',
  'general-show_author_in_blog' => '1',
  'general-tracking_code' => '',
  'general-favicon' => '',
  'general-show_rel_posts' => '1',
  'general-rel_posts_head_title' => 'Related posts',
  'general-rel_posts_max' => 6,
  'general-show_rel_projects' => '1',
  'general-rel_projects_head_title' => 'Related projects',
  'general-rel_projects_max' => 16,
  'general-rel_projects_title' => '1',
  'general-rel_projects_excerpt' => '0',
  'general-rel_projects_link' => '1',
  'general-rel_projects_details' => '1',
  'general-rel_projects_fullwidth_height' => 210,
  'general-rel_projects_height' => 205,
  'general-blog_meta_on' => '1',
  'general-blog_meta_postformat' => '1',
  'general-blog_meta_date' => '1',
  'general-blog_meta_author' => '1',
  'general-blog_meta_categories' => '1',
  'general-blog_meta_comments' => '1',
  'general-blog_meta_tags' => '1',
  'general-portfolio_meta_on' => '1',
  'general-portfolio_meta_date' => '1',
  'general-portfolio_meta_author' => false,
  'general-portfolio_meta_categories' => '1',
  'general-portfolio_meta_comments' => '1',
  'fonts-font_family' => 'Arial',
  'fonts-normal_size' => 14,
  'fonts-small_size' => 12,
  'fonts-big_size' => 15,
  'fonts-line_height' => 22,
  'fonts-h1_font_family' => 'Open Sans:300',
  'fonts-h1_font_size' => 51,
  'fonts-h1_line_height' => 60,
  'fonts-h1_uppercase' => false,
  'fonts-h2_font_family' => 'Open Sans:300',
  'fonts-h2_font_size' => 38,
  'fonts-h2_line_height' => 44,
  'fonts-h2_uppercase' => false,
  'fonts-h3_font_family' => 'Open Sans',
  'fonts-h3_font_size' => 24,
  'fonts-h3_line_height' => 30,
  'fonts-h3_uppercase' => false,
  'fonts-h4_font_family' => 'Open Sans',
  'fonts-h4_font_size' => 18,
  'fonts-h4_line_height' => 24,
  'fonts-h4_uppercase' => false,
  'fonts-h5_font_family' => 'Open Sans',
  'fonts-h5_font_size' => 16,
  'fonts-h5_line_height' => 22,
  'fonts-h5_uppercase' => false,
  'fonts-h6_font_family' => 'Arial',
  'fonts-h6_font_size' => 14,
  'fonts-h6_line_height' => 22,
  'fonts-h6_uppercase' => false,
  'buttons-s_font_family' => 'Open Sans',
  'buttons-s_font_size' => 12,
  'buttons-s_uppercase' => false,
  'buttons-s_line_height' => 25,
  'buttons-m_font_family' => 'Open Sans',
  'buttons-m_font_size' => 13,
  'buttons-m_uppercase' => false,
  'buttons-m_line_height' => 30,
  'buttons-l_font_family' => 'Open Sans',
  'buttons-l_font_size' => 17,
  'buttons-l_uppercase' => false,
  'buttons-l_line_height' => 39,
  'top_bar-show' => '1',
  'top_bar-bg_color' => '#ffffff',
  'top_bar-bg_opacity' => 100,
  'top_bar-bg_ie_color' => '#ffffff',
  'top_bar-bg_image' => 
  array (
    'image' => '',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'center',
  ),
  'top_bar-text_color' => '#838992',
  'top_bar-dividers_color' => '#838992',
  'top_bar-dividers_opacity' => 25,
  'top_bar-dividers_ie_color' => '#dadbde',
  'top_bar-contact_show' => '1',
  'top_bar-contact_address' => '102580 Santa Monica BLVD Los Angeles',
  'top_bar-contact_phone' => '+3 045 224 33 12',
  'top_bar-contact_email' => 'info@yoursite.com',
  'top_bar-contact_skype' => 'YourSkype',
  'top_bar-contact_clock' => '',
  'top_bar-contact_info' => '',
  'header-bg_color' => '#232c3a',
  'header-bg_image' => 
  array (
    'image' => '/wp-content/themes/dt-the7/images/backgrounds/set-1/full/patt23.png',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'top',
  ),
  'header-bg_height' => 106,
  'header-layout' => 'left',
  'header-contentarea' => '<p><span class="paint-accent-color">Address:</span>  102580 Santa Monica BLVD Los Angeles
</p>
<span class="paint-accent-color">Phone: </span> +3 045 224 33 12, 220 30 22',
  'header-contentarea_color' => '#ffffff',
  'header-font_family' => 'Open Sans',
  'header-font_size' => 15,
  'header-font_uppercase' => false,
  'header-font_line_height' => 34,
  'header-font_color' => '#ffffff',
  'header-menu_bg_color' => '#838992',
  'header-menu_bg_opacity' => 30,
  'header-menu_bg_ie_color' => '#3a3f4a',
  'header-submenu_parent_clickable' => false,
  'header-submenu_color' => '#373a41',
  'header-submenu_bg_color' => '#ffffff',
  'header-submenu_bg_opacity' => 97,
  'header-submenu_bg_ie_color' => '#ffffff',
  'header-submenu_dividers_color' => '#001525',
  'header-submenu_dividers_opacity' => 10,
  'header-submenu_dividers_ie_color' => '#dadee1',
  'header-search_show' => '1',
  'slideshow-bg_color' => 'f7f7f8',
  'slideshow-bg_opacity' => 100,
  'slideshow-bg_ie_color' => '#ffffff',
  'slideshow-bg_image' => 
  array (
    'image' => '',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'top',
  ),
  'slideshow-bg_fullscreen' => false,
  'content-headers_color' => '#373a41',
  'content-primary_text_color' => '#838992',
  'content-dividers_color' => '#838992',
  'content-dividers_opacity' => 25,
  'content-dividers_ie_color' => '#dadbde',
  'stripes-stripe_1_color' => '#232c3a',
  'stripes-stripe_1_opacity' => 100,
  'stripes-stripe_1_ie_color' => '#f7f7f8',
  'stripes-stripe_1_bg_image' => 
  array (
    'image' => '/wp-content/themes/dt-the7/images/backgrounds/set-1/full/patt23.png',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'center',
  ),
  'stripes-stripe_1_headers_color' => '#ffffff',
  'stripes-stripe_1_text_color' => '#838992',
  'stripes-stripe_1_div_color' => '#838992',
  'stripes-stripe_1_div_opacity' => 30,
  'stripes-stripe_1_div_ie_color' => '#3a3f4a',
  'stripes-stripe_2_color' => '#232c3a',
  'stripes-stripe_2_opacity' => 100,
  'stripes-stripe_2_ie_color' => '#f7f7f8',
  'stripes-stripe_2_bg_image' => 
  array (
    'image' => '/wp-content/themes/dt-the7/images/backgrounds/set-1/full/patt23.png',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'top',
  ),
  'stripes-stripe_2_headers_color' => '#ffffff',
  'stripes-stripe_2_text_color' => '#838992',
  'stripes-stripe_2_div_color' => '#838992',
  'stripes-stripe_2_div_opacity' => 30,
  'stripes-stripe_2_div_ie_color' => '#3a3f4a',
  'stripes-stripe_3_color' => '#f7f7f8',
  'stripes-stripe_3_opacity' => 100,
  'stripes-stripe_3_ie_color' => '#cacaca',
  'stripes-stripe_3_bg_image' => 
  array (
    'image' => '/inc/presets/images/full/skin5.stripes-stripe-3-bg-image.jpg',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'top',
  ),
  'stripes-stripe_3_headers_color' => '#232c3a',
  'stripes-stripe_3_text_color' => '#838992',
  'stripes-stripe_3_div_color' => '#838992',
  'stripes-stripe_3_div_opacity' => 30,
  'stripes-stripe_3_div_ie_color' => '#dadbde',
  'sidebar-bg_color' => '#f7f7f8',
  'sidebar-bg_opacity' => 100,
  'sidebar-bg_ie_color' => '#ffffff',
  'sidebar-bg_image' => 
  array (
    'image' => '',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'center',
  ),
  'sidebar-dividers_color' => '#838992',
  'sidebar-dividers_opacity' => 25,
  'sidebar-dividers_ie_color' => '#dadbde',
  'sidebar-headers_color' => '#373a41',
  'sidebar-primary_text_color' => '#838992',
  'footer-bg_color' => '#232c3a',
  'footer-bg_opacity' => 100,
  'footer-bg_ie_color' => '#1B1B1B',
  'footer-bg_image' => 
  array (
    'image' => '/wp-content/themes/dt-the7/images/backgrounds/set-1/full/patt23.png',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'top',
  ),
  'footer-dividers_color' => '#838992',
  'footer-dividers_opacity' => 30,
  'footer-dividers_ie_color' => '#3a3f4a',
  'footer-headers_color' => '#ffffff',
  'footer-primary_text_color' => '#838992',
  'bottom_bar-bg_color' => '#ffffff',
  'bottom_bar-bg_opacity' => 100,
  'bottom_bar-bg_ie_color' => '#ffffff',
  'bottom_bar-bg_image' => 
  array (
    'image' => '',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'top',
  ),
  'bottom_bar-color' => '#838992',
  'bottom_bar-dividers_color' => '#838992',
  'bottom_bar-dividers_opacity' => 25,
  'bottom_bar-dividers_ie_color' => '#dadbde',
  'bottom_bar-copyrights' => '',
  'bottom_bar-credits' => '1',
  'hoover-color' => '#ffffff',
  'hoover-opacity' => 25,
  'hoover-style' => 'blur',
  'general-rel_projects_fullwidth_width_style' => 'fixed',
  'general-rel_projects_fullwidth_width' => 210,
  'general-rel_projects_width_style' => 'fixed',
  'general-rel_projects_width' => 205,
  'general-rel_projects_meta' => '0',
  'top_bar-soc_ico_facebook' => 'https://www.facebook.com/WordPress.Premium.Theme',
  'top_bar-soc_ico_twitter' => 'https://twitter.com/premium_theme',
  'top_bar-soc_ico_google' => '',
  'top_bar-soc_ico_dribbble' => 'http://dribbble.com/dream-theme',
  'top_bar-soc_ico_you-tube' => '',
  'top_bar-soc_ico_rss' => '',
  'top_bar-soc_ico_delicious' => '',
  'top_bar-soc_ico_flickr' => '',
  'top_bar-soc_ico_forrst' => '',
  'top_bar-soc_ico_lastfm' => '',
  'top_bar-soc_ico_linkedin' => '',
  'top_bar-soc_ico_vimeo' => '',
  'top_bar-soc_ico_tumbler' => '',
  'top_bar-soc_ico_pinterest' => 'http://www.pinterest.com/dreamtheme/boards/',
  'top_bar-soc_ico_devian' => '',
  'top_bar-soc_ico_skype' => '',
  'top_bar-soc_ico_github' => '',
  'top_bar-soc_ico_instagram' => 'http://instagram.com/dream_theme_photo',
  'top_bar-soc_ico_stumbleupon' => '',
  'top_bar-soc_ico_behance' => '',
  'top_bar-soc_ico_mail' => '',
  'top_bar-soc_ico_website' => '',
  'top_bar-soc_ico_px-500' => '',
  'top_bar-soc_ico_tripedvisor' => '',
  'top_bar-soc_ico_vk' => '',
  'top_bar-soc_icon_color' => '#c1c5ca',
  'general-custom_css' => '',
  'general-border_radius' => 8,
  'header-transparent_bg_color' => '#0b1016',
  'header-transparent_bg_opacity' => 65,
  'header-transparent_bg_ie_color' => '#000000',
  'header-transparent_bg_image' => 
  array (
    'image' => '',
    'repeat' => 'repeat',
    'position_x' => 'center',
    'position_y' => 'center',
  ),
  'top_bar-text' => '',
  'bottom_bar-text' => '',
  'general-woocommerce_show_mini_cart_in_top_bar' => '1',
  'general-title_align' => 'center',
  'general-show_breadcrumbs' => '1',
  'general-floating_menu_show_logo' => '1',
  'general-floating_menu_logo_regular' => 
  array (
    0 => '/inc/presets/images/full/skin5.general-floating-menu-logo-regular.png?w=27&h=53',
    1 => 0,
  ),
  'general-floating_menu_logo_hd' => 
  array (
    0 => '/inc/presets/images/full/skin5.general-floating-menu-logo-hd.png?w=54&h=106',
    1 => 0,
  ),
); ?>